import { ArrowLeft, Mic, Phone, Send } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function DoctorChatThreadPage() {
  const navigate = useNavigate()
  const [input, setInput] = useState('')
  const [messages, setMessages] = useState([{ text: 'Good morning, Ramesh. How are you feeling today?', mine: false, time: '9:02 AM' }, { text: 'A little tired, but I did my memory game already.', mine: true, time: '9:05 AM' }, { text: "That's wonderful. I saw your scores. Don't forget your 2 PM medicine.", mine: false, time: '9:06 AM' }])
  const send = (value = input) => { if (!value.trim()) return; const now = new Date(); setMessages((items) => [...items, { text: value.trim(), mine: true, time: now.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) }]); setInput('') }

  return <div className="min-h-screen bg-canvas font-ui flex flex-col">
    <div className="chat-header px-4.5 pt-11 pb-3.5 bg-white shadow-sm flex items-center gap-3"><button onClick={() => navigate('/doctor/chat')} aria-label="Back" className="w-[38px] h-[38px] rounded-xl bg-brand-green-tint flex items-center justify-center flex-shrink-0"><ArrowLeft size={19} className="text-brand-green" strokeWidth={2.6} /></button><div className="w-11 h-11 rounded-full bg-brand-green text-white flex items-center justify-center font-extrabold text-sm flex-shrink-0">RK</div><div className="min-w-0 flex-1"><h1 className="m-0 text-[15.5px] font-extrabold text-ink truncate">Ramesh Kulkarni</h1><p className="m-0 mt-0.5 text-[11.5px] font-bold text-brand-green">● Online</p></div><button onClick={() => window.location.href = 'tel:+919800002101'} aria-label="Call" className="w-[38px] h-[38px] rounded-xl bg-brand-green-tint flex items-center justify-center"><Phone size={18} className="text-brand-green" /></button></div>
    <div className="flex-1 overflow-y-auto px-4 py-4 flex flex-col gap-3"> <div className="text-center text-[11px] font-extrabold text-ink-soft my-1.5">Today</div>{messages.map((message, index) => <div key={`${message.time}-${index}`}><div className={`flex ${message.mine ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[76%] px-3.5 py-2.75 rounded-[18px] text-sm font-bold leading-relaxed ${message.mine ? 'bg-brand-green text-white rounded-br-[5px]' : 'bg-white text-ink shadow-sm rounded-bl-[5px]'}`}>{message.text}</div></div><div className={`text-[10px] font-bold text-ink-soft mt-1 ${message.mine ? 'text-right' : ''}`}>{message.time}</div></div>)}</div>
    <div className="px-4 pb-2 flex gap-2 overflow-x-auto"><button onClick={() => send("I'm feeling fine")} className="flex-shrink-0 bg-white border border-brand-green-tint text-brand-green font-extrabold text-xs px-3.5 py-2 rounded-full">I&apos;m feeling fine</button><button onClick={() => send('I need an appointment')} className="flex-shrink-0 bg-white border border-brand-green-tint text-brand-green font-extrabold text-xs px-3.5 py-2 rounded-full">I need an appointment</button></div>
    <div className="bg-white px-3.5 pt-2.5 pb-5.5 flex items-center gap-2 shadow-[0_-6px_16px_rgba(36,50,42,0.06)]"><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && send()} placeholder="Type a message..." className="flex-1 bg-canvas rounded-full px-4 py-3 text-sm font-bold text-ink outline-none" /><button onClick={() => {}} aria-label="Speak message" className="w-11 h-11 rounded-full bg-marigold-tint flex items-center justify-center"><Mic size={19} className="text-marigold" /></button><button onClick={() => send()} aria-label="Send message" className="w-11 h-11 rounded-full bg-brand-green flex items-center justify-center"><Send size={19} className="text-white" /></button></div>
  </div>
}
